# Generated by Django 4.2.4 on 2024-02-21 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCounselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='counselor',
            name='user',
        ),
        migrations.AlterField(
            model_name='counselor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='CounselingAppointment',
        ),
        migrations.AddField(
            model_name='appointmentcounselling',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicapp.counselor'),
        ),
        migrations.AddField(
            model_name='appointmentcounselling',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
