# Generated by Django 4.2.4 on 2024-04-02 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('outof_rating', models.IntegerField(default=5, editable=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_status', models.CharField(choices=[('reviewed', 'reviewed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicapp.counselor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
