# Generated by Django 4.2.4 on 2023-09-02 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0008_rename_treatment_day_treatment_ment_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
    ]
