# Generated by Django 4.2.4 on 2023-09-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0013_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
