# Generated by Django 4.2.4 on 2023-09-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0019_doctor_email_alter_doctor_license_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
