# Generated by Django 4.2.4 on 2023-09-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0020_alter_doctor_email_alter_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='license_no',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
    ]
