# Generated by Django 4.2.4 on 2023-09-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0031_remove_doctor_status_doctor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
