# Generated by Django 4.2.4 on 2023-09-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0033_remove_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
