# Generated by Django 4.2.4 on 2023-09-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0034_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
