# Generated by Django 4.2.4 on 2023-09-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0036_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
    ]
