# Generated by Django 4.2.4 on 2023-10-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0040_remove_payment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success')], default='Pending', max_length=10),
        ),
    ]
