# Generated by Django 4.2.4 on 2024-01-30 04:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicapp', '0042_prescriptionrefillrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrescriptionRefillRequest',
            new_name='PrescriptionRefill',
        ),
    ]
