# Generated by Django 4.2.4 on 2024-02-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0046_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
