# Generated by Django 4.2.4 on 2024-02-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0049_appointmentcounselling'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcounselling',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
