# Generated by Django 4.2.4 on 2024-02-22 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0052_counselingfeedback_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselingfeedback',
            name='session_date',
        ),
    ]
