# Generated by Django 4.2.4 on 2024-03-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0053_remove_counselingfeedback_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
