# Generated by Django 4.2.4 on 2024-03-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0054_counselor_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='healthcare_tips/')),
            ],
        ),
    ]
