# Generated by Django 4.2.4 on 2024-03-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0055_healthcaretip'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcaretip',
            name='bookmarks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthcaretip',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthcaretip',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
    ]
