# Generated by Django 4.2.4 on 2024-03-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0056_healthcaretip_bookmarks_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicapp.healthcaretip')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkedTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicapp.healthcaretip')),
            ],
        ),
    ]
