# Generated by Django 4.2.4 on 2024-03-12 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0058_counselingreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounselingReport',
        ),
    ]
