# Generated by Django 4.2.4 on 2024-03-12 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicapp', '0059_delete_counselingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_session', models.DateField()),
                ('summary', models.TextField()),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
