# Generated by Django 4.2.4 on 2024-03-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0061_healthmetric_delete_counselingreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthmetric',
            name='metric_type',
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='value',
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='blood_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='body_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='cholesterol_hdl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='cholesterol_ldl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='physical_activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
