# Generated by Django 4.2.4 on 2024-03-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0062_remove_healthmetric_metric_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetric',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
