# Generated by Django 4.2.4 on 2024-03-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0064_ambulance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='service_name',
        ),
    ]
