# Generated by Django 4.2.4 on 2024-03-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0065_remove_ambulance_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='service_status',
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='vehicle_capacity',
            field=models.IntegerField(),
        ),
    ]
