# Generated by Django 4.2.4 on 2024-03-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0066_remove_ambulance_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='counselor',
            name='certification',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='counselor',
            name='available_time_slots',
            field=models.ManyToManyField(blank=True, related_name='counselors', to='medicapp.timeslot'),
        ),
    ]
