# Generated by Django 4.2.4 on 2024-03-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0067_timeslot_counselor_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselor',
            name='available_time_slots',
        ),
        migrations.RemoveField(
            model_name='counselor',
            name='certification',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
