# Generated by Django 4.2.4 on 2024-03-26 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicapp', '0068_remove_counselor_available_time_slots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthmetric',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='body_temperature',
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='cholesterol_hdl',
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='cholesterol_ldl',
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='height',
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='physical_activity',
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='sleep_duration',
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='exercise_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
